Add friends likes
AleksandrGimanov/java-filmorate pull request #2
Opened 2023-02-23 21:58 UTC by AleksandrGimanov

2023-02-25 04:01 UTC, z8q requested changes
Привет!
Комментарии оставил

2023-02-25 04:01 UTC, z8q commented on src/test/java/ru/yandex/practicum/filmorate/controllerTests/FilmControllerTest.java
> +public class FilmControllerTest  {
В тестах стоит проверить работу добавления/удаления друзей и лайков

2023-02-25 04:01 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        checkUsers(List.of(userId,friendId));
Тут двойная проверка на наличие user в checkUsers и внутри getUserById

2023-02-25 04:01 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Map<Integer, User> getUsers() {
Не уверен, что хорошая идея открывать доступ к мапе.
Рекомендую обращаться к ней только из методов UserStorage, работа с хранилищем все таки ведется только в этом классе

2023-02-25 04:01 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUserById(userId).getUsersFriends().stream()
У HashSet есть метод retainAll(), можно тоже посмотреть,  как работает

2023-02-25 04:01 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Map<Integer, Film> getFilms(){
Не уверен, что хорошая идея открывать доступ к мапе.
Рекомендую обращаться к ней только из методов FilmStorage, работа с хранилищем все таки ведется только в этом классе

2023-02-25 08:37 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Map<Integer, Film> getFilms(){
Удалил, оставил реализацию через getFilmById

2023-02-25 08:38 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Map<Integer, User> getUsers() {
Удалил, оставил реализацию через getUserById

2023-02-25 08:39 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        checkUsers(List.of(userId,friendId));
Удалил, оставил только 1 метод

2023-02-25 15:37 UTC, AleksandrGimanov commented on src/test/java/ru/yandex/practicum/filmorate/controllerTests/FilmControllerTest.java
> +public class FilmControllerTest  {
В тз не было об этом условия, я попробовал сделать, но чет не получилось реализовать

2023-02-26 09:44 UTC, z8q approved these changes

2023-03-05 13:26 UTC, merged