11 спринт база
AleksandrGimanov/java-filmorate pull request #3
Opened 2023-03-21 07:38 UTC by AleksandrGimanov

2023-03-21 18:21 UTC, z8q requested changes

2023-03-21 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/contoller/FilmController.java
>      private final FilmService filmService;
POST запрос http://localhost:8080/films/ c таким body:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"duration": 1234567,
	"rating": 100,
	"mpa": {
		"id": 5,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [ `Не добавил id`
		{
			"name": "action"
		},
		{
			"name": "drama"
		},
		{
			"name": "comedy"
		}
	]
}
Приводит к ошибке:
{
	"timestamp": "2023-03-21T17:44:02.508+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films/"
}
Но файл при этом все равно сохраняется.
А если такой запрос:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"duration": 1234567,
	"rating": 100,
	"mpa": { `Не указал id в mpa`
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{
			"id": 1,
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}
Такой запрос возвращает:
{
	"timestamp": "2023-03-21T17:50:03.041+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films/"
}
И объект не сохраняется.
Лучше, чтобы при ошибках объект всегда не сохранялся

2023-03-21 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/contoller/UserController.java
> +    public void addFriend(@PathVariable int id, @PathVariable int friendId) {
Похоже допускается добавление в друзья одного userа несколько раз.
После нескольких добавлений такой GET http://localhost:8080/users/3/friends/common/2 вернул:
[
	{
		"id": 1,
		"email": "a@yandex.ru",
		"login": "BobLogin",
		"name": "Bob",
		"birthday": "2011-11-11"
	},
	{
		"id": 1,
		"email": "a@yandex.ru",
		"login": "BobLogin",
		"name": "Bob",
		"birthday": "2011-11-11"
	}
]

2023-03-21 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Getter
Хотелось бы, чтобы на get запросы для получения всех фильмов или всех юзеров, списки лайков/друзей тоже выводились

2023-03-21 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +    MapperUser mapperUser;
private

2023-03-22 06:10 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/contoller/UserController.java
> +    public void addFriend(@PathVariable int id, @PathVariable int friendId) {
Добавил проверку на дубликаты, исправил

2023-03-22 08:01 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +    MapperUser mapperUser;
поправил

2023-03-22 08:03 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Getter
попробовал, при добавлении 
SELECT f.*,count(fl.user_id) likes FROM FILMS as f 
right join films_likes as fl on f.id= fl.film_id
group by f.id 
нарушается группировка и тесты не проходят в постмане. решил оставить как есть

2023-03-22 09:33 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/contoller/FilmController.java
>      private final FilmService filmService;
Привет Кирилл, с первым пояснением не получается придумать действие к genre с пустым id. Ведь первым делом  создается фильм по первому инсерту со значениями из таблицы Films. Затем к нему втором инсертом записываются поля жанра. поэтому вне зависимости от правильности запроса жанра фильм будет в базе существовать. если пытаться удалить фильм при неправильности подачи жанра то это только после добавления в базу можно сделать , но тогда тесты не пройдут из постмана, в них при создании жанр не указывается.

2023-03-22 09:36 UTC, merged

2023-03-22 14:07 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/contoller/FilmController.java
>      private final FilmService filmService;
все же победил я эту проблему

2023-03-22 19:05 UTC, z8q commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
В тз зависимость не требовалась